### DISCUSSION TITLE
Using env together with "Untyped wrapper"-approach

### DISCUSSION THREAD

**Discussion by uweschaefer** [typesafegithub/github-workflows-kt#412] [Q&A] [answered]
Hi, 

i am try to follow the "Untyped wrapper" approach mentioned here https://krzema12.github.io/github-actions-kotlin-dsl/user-guide/using-actions/ in order to use an - yet unsupported - action. 
I am struggeling a bit to find out, how to add env-variables to the action.

here is what i am trying to produce:
```yaml
 - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
```

Any leads, that i don't currently see?

Thanks.

**Comment by uweschaefer** [comment, marked as answer]
**[Solved]**

Ok, now i found it - stupid me. 

example: 
```kotlin
        uses(
            action = customAction,
            name = "Sonar analysis",
            env = linkedMapOf(
                "GITHUB_TOKEN" to expr { secrets.GITHUB_TOKEN }, // typesafe
                "SONAR_TOKEN" to expr { "secrets.SONAR_TOKEN" } // just as a string
            )
        )
``` 
with custom action being
```kotlin
val customAction = CustomAction(
    actionOwner = "SonarSource",
    actionName = "sonarcloud-github-action",
    actionVersion = "master",
    inputs = linkedMapOf()
)
```
to produce
```
      - id: step-6
        name: Sonar analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
```
