### ISSUE TITLE
[Bug] Incorrect type for `GradleBuildActionV3.buildScanTermsOfServiceAgree`

### ISSUE THREAD

**Issue by DennisTsar** [typesafegithub/github-workflows-kt#1264]
# Action

The docs for `buildScanTermsOfServiceAgree` state
> This input value must be "yes".

but the action provides a boolean parameter
```kt
GradleBuildActionV3(
    buildScanTermsOfServiceAgree = true
)
```

# Expected

```yaml
uses: 'gradle/gradle-build-action@v3'
with:
  build-scan-terms-of-service-agree: 'yes'
```
either by automatically converting "true" to "yes" or by changing the API to accept a string value:
```kt
GradleBuildActionV3(
    buildScanTermsOfServiceAgree = "yes"
)
```

# Actual

```yaml
uses: 'gradle/gradle-build-action@v3'
with:
  build-scan-terms-of-service-agree: 'true'
```

# Workaround, if exists

```kt
GradleBuildActionV3(
    _customInputs = mapOf("build-scan-terms-of-service-agree" to "yes")
)
```

# Library version

v1.11.0
