### ISSUE TITLE
[Core feature request] Support for getting full uses string and action inputs as string

### ISSUE THREAD

**Issue by Vampire** [typesafegithub/github-workflows-kt#1583]
This time I have an actually rather specific request.
I'm in the need of retrying a step on error due to environmental flakiness.

I found an action that seems to be very nice for that and not only supporting run actions, but also many regular and docker actions: https://github.com/marketplace/actions/retry-action

For the non-run actions, you give it the `uses` string and the action inputs as YAML-style string.

It would be nice if we had some possibility to support this nicely using this lib.

Currently, in simple cases, i. e. only single-line values and no need for YAML escaping due to reserved keywords or similar, you can do something like (of course in the end refactored into some util extension function):
```kotlin
val setupJava11 = SetupJava(
    javaVersion = "11",
    distribution = Temurin
)

uses(
    name = "Setup Java 11",
    action = WretryAction(
        action = setupJava11.let { "${it.actionOwner}/${it.actionName}@${it.actionVersion}" },
        with = setupJava11.toYamlArguments().entries.joinToString("\n") { (key, value) ->
            "$key: $value"
        }
    )
)
```

But this is a bit ugly, you need to copy it between projects, and more complex cases like escaping needed or multi-line strings are not supported by this.

It would be awesome if we would have some methods helping with this so that it more looks something like:
```kotlin
val setupJava11 = SetupJava(
    javaVersion = "11",
    distribution = Temurin
)

uses(
    name = "Setup Java 11",
    action = WretryAction(
        action = setupJava11.usesString,
        with = setupJava11.inputsYaml
    )
)
```

**Comment by krzema12** [comment]
Quick idea, haven't tested it. How about making https://github.com/typesafegithub/github-workflows-kt/blob/0bea0bf49cabdce357263211c7f1f27a75424ec4/github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/domain/actions/Action.kt#L10 public, and then retrieving the args with https://github.com/typesafegithub/github-workflows-kt/blob/0bea0bf49cabdce357263211c7f1f27a75424ec4/github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/domain/actions/Action.kt#L6 and passing them to the retry action with _customArguments?

**Comment by Vampire** [comment]
Right about the first part I guess, hence the naming I used :-)

---

The second part is probably not so easy, as
- the values in `toYamlArguments()` are not yet yamlified
- would be serialized as "sub-map", not as `String`
- needs to then specify all inputs in `_customArguments`

So
```kotlin
val setupJava11 = SetupJava(
    javaVersion = """
        11
        12
    """.trimIndent(),
    distribution = Temurin
)
uses(
    name = "Setup Java 11",
    action = WretryActionMain(),
    _customArguments = mapOf(
        "with" to mapOf(
            "action" to setupJava11.usesString,
            "with" to setupJava11.toYamlArguments()
        )
    )
)
```
would become
```yaml
- id: 'step-4'
  name: 'Checkout'
  uses: 'actions/checkout@v4'
- id: 'step-5'
  name: 'Setup Java 11'
  uses: 'Wandalen/wretry.action/main@v3'
  with:
    action: 'actions/setup-java@v4'
    with:
      java-version: |-
        11
        12
      distribution: 'temurin'
```
while as far as I understood their docs it would need to be
```yaml
- id: 'step-4'
  name: 'Checkout'
  uses: 'actions/checkout@v4'
- id: 'step-5'
  name: 'Setup Java 11'
  uses: 'Wandalen/wretry.action/main@v3'
  with:
    action: 'actions/setup-java@v4'
    with: |-
      java-version: |-
        11
        12
      distribution: 'temurin'
```

I've had a quick look at their sources and they use the `with` string and give it to `js-yaml`'s `load` method to parse it: https://github.com/Wandalen/wretry.action/blob/js_action/src/Common.js#L104-L105

I'm not sure whether GHA would accept an actual YAML map there and make it an actually parseable YAML string before giving it to the action?
