### ISSUE TITLE
[Core feature request] `vars` context

### ISSUE THREAD

**Issue by Vampire** [typesafegithub/github-workflows-kt#1955]
**What feature do you need?**
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#vars-context

**Do you have an example usage?**
```
    - id: 'step-4'
      name: 'Create GitHub App Token'
      uses: 'actions/create-github-app-token@v2'
      with:
        app-id: '${{ vars.APP_CLIENT_ID }}'
        private-key: '${{ secrets.APP_PRIVATE_KEY }}'
        permission-checks: 'write'
        permission-pull-requests: 'write'
```
