### ISSUE TITLE
[Core feature request] More sophisticated `uses` strings

### ISSUE THREAD

**Issue by Vampire** [typesafegithub/github-workflows-kt#288]
**What feature do you need?**
From https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-public-action
you can see that `uses` can be more than just `{owner}/{repo}@{ref}`.
It can also be `{owner}/{repo}/{path}@{ref}`, a local path within the current worktree, or a docker image.

In my current case I'd need the local path variant.

**Do you have an example usage?**
```yml
- id: "execute_action"
  uses: "./"
  with:
    "distribution": "${{ matrix.distribution.user-id }}"
  continue-on-error: true
- run: "if '${{ steps.execute_action.outcome }}' NEQ 'failure' exit 1\n"
  shell: "cmd"
```
