### ISSUE TITLE
[Core feature request] Job service containers

### ISSUE THREAD

**Issue by kugo12** [typesafegithub/github-workflows-kt#883]
**What feature do you need?**
https://docs.github.com/en/actions/using-containerized-services/about-service-containers
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idservices

**Do you have an example usage?**
```yaml
gradle-test:
  runs-on: ubuntu-latest
  services:
    postgres:
      image: postgres:14-alpine
      env:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: test
      ports: ["5432:5432"]
      options: >-
        --health-cmd pg_isready
        --health-interval 2s
        --health-timeout 2s
        --health-retries 30
    rabbitmq:
      image: rabbitmq:3.12-alpine
      ports: ["5672:5672"]
      env:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
      options: >-
        --health-cmd "rabbitmq-diagnostics -q ping"
        --health-interval 2s
        --health-timeout 2s
        --health-retries 30
```

**Is there a workaround for not having this feature? If yes, please describe it.**
Using _customArguments
